/**
 * Contract ABIs for Cruzible protocol interactions.
 *
 * Minimal ABI definitions for the functions the frontend needs to call.
 * Full ABIs are generated by Foundry/Hardhat compilation.
 */

export const CruzibleABI = [
  // --- Read Functions ---
  {
    name: "totalPooledAethel",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "totalShares",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "getExchangeRate",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "currentEpoch",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "getUserWithdrawals",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "user", type: "address" }],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        components: [
          { name: "id", type: "uint256" },
          { name: "shares", type: "uint256" },
          { name: "aethelAmount", type: "uint256" },
          { name: "requestTime", type: "uint256" },
          { name: "completionTime", type: "uint256" },
          { name: "claimed", type: "bool" },
        ],
      },
    ],
  },
  {
    name: "effectiveAPY",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "isWithdrawalClaimable",
    type: "function",
    stateMutability: "view",
    inputs: [
      { name: "user", type: "address" },
      { name: "withdrawalId", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },

  // --- Write Functions ---
  {
    name: "stake",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [{ name: "shares", type: "uint256" }],
  },
  {
    name: "stakeWithReferral",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "amount", type: "uint256" },
      { name: "referralCode", type: "uint256" },
    ],
    outputs: [{ name: "shares", type: "uint256" }],
  },
  {
    name: "unstake",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "shares", type: "uint256" }],
    outputs: [
      { name: "withdrawalId", type: "uint256" },
      { name: "aethelAmount", type: "uint256" },
    ],
  },
  {
    name: "withdraw",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "withdrawalId", type: "uint256" }],
    outputs: [],
  },
  {
    name: "batchWithdraw",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "withdrawalIds", type: "uint256[]" }],
    outputs: [],
  },
  {
    name: "claimRewards",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "epoch", type: "uint256" },
      { name: "amount", type: "uint256" },
      { name: "proof", type: "bytes32[]" },
    ],
    outputs: [],
  },

  // --- Events ---
  {
    name: "Staked",
    type: "event",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "shares", type: "uint256", indexed: false },
    ],
  },
  {
    name: "Unstaked",
    type: "event",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "shares", type: "uint256", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
      { name: "withdrawalId", type: "uint256", indexed: false },
    ],
  },
  {
    name: "Withdrawn",
    type: "event",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "withdrawalId", type: "uint256", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    name: "RewardsClaimed",
    type: "event",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "epoch", type: "uint256", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
] as const;

export const StAETHELABI = [
  {
    name: "balanceOf",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "sharesOf",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "getSharesByAethel",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "aethelAmount", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "getAethelByShares",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "sharesAmount", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "getExchangeRate",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "getTotalShares",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "totalSupply",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "approve",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    name: "allowance",
    type: "function",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
] as const;

export const ERC20ABI = [
  {
    name: "approve",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    name: "allowance",
    type: "function",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "balanceOf",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
] as const;

// ---------------------------------------------------------------------------
// InstitutionalStablecoinBridge — Minimal ABI for frontend interactions
// ---------------------------------------------------------------------------

export const StablecoinBridgeABI = [
  // --- Read Functions ---
  {
    name: "stablecoins",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "assetId", type: "bytes32" }],
    outputs: [
      { name: "enabled", type: "bool" },
      { name: "mintPaused", type: "bool" },
      { name: "routingType", type: "uint8" },
      { name: "token", type: "address" },
      { name: "tokenMessengerV2", type: "address" },
      { name: "messageTransmitterV2", type: "address" },
      { name: "proofOfReserveFeed", type: "address" },
      { name: "mintCeilingPerEpoch", type: "uint256" },
      { name: "dailyTxLimit", type: "uint256" },
      { name: "hourlyOutflowBps", type: "uint16" },
      { name: "dailyOutflowBps", type: "uint16" },
      { name: "porDeviationBps", type: "uint16" },
      { name: "porHeartbeatSeconds", type: "uint48" },
    ],
  },

  // --- Write Functions ---
  {
    name: "bridgeOutViaCCTP",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "assetId", type: "bytes32" },
      { name: "amount", type: "uint256" },
      { name: "destinationDomain", type: "uint32" },
      { name: "mintRecipient", type: "bytes32" },
    ],
    outputs: [{ name: "cctpNonce", type: "uint64" }],
  },

  // --- Events ---
  {
    name: "StablecoinConfigured",
    type: "event",
    inputs: [
      { name: "assetId", type: "bytes32", indexed: true },
      { name: "token", type: "address", indexed: true },
      { name: "routingType", type: "uint8", indexed: false },
      { name: "enabled", type: "bool", indexed: false },
    ],
  },
  {
    name: "CCTPBurnInitiated",
    type: "event",
    inputs: [
      { name: "assetId", type: "bytes32", indexed: true },
      { name: "sender", type: "address", indexed: true },
      { name: "destinationDomain", type: "uint32", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "cctpNonce", type: "uint64", indexed: false },
    ],
  },
  {
    name: "MintExecuted",
    type: "event",
    inputs: [
      { name: "assetId", type: "bytes32", indexed: true },
      { name: "mintOperationId", type: "bytes32", indexed: true },
      { name: "recipient", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    name: "CircuitBreakerTriggered",
    type: "event",
    inputs: [
      { name: "assetId", type: "bytes32", indexed: true },
      { name: "reasonCode", type: "bytes32", indexed: true },
      { name: "observed", type: "uint256", indexed: false },
      { name: "threshold", type: "uint256", indexed: false },
    ],
  },
  {
    name: "ReserveCheckPerformed",
    type: "event",
    inputs: [
      { name: "assetId", type: "bytes32", indexed: true },
      { name: "reserveAmount18", type: "uint256", indexed: false },
      { name: "liabilities18", type: "uint256", indexed: false },
      { name: "deviationBps", type: "uint256", indexed: false },
      { name: "heartbeatStale", type: "bool", indexed: false },
    ],
  },
] as const;
